### ISSUE TITLE
Log dirs in /var/log

### ISSUE THREAD

**Issue by vforgione** [5thColumn/ansible-role-spark#4]
Logs traditionally go in `/var/log/${your app name here}`. Is there a reason to put it in the user's home?

https://github.com/Prajaktcs/ansible-role-spark/blob/master/defaults/main.yml#L13

**Comment by dm00000** [comment]
Please update the status of this issue. Is this still a problem or has it been addressed already in subsequent PR's?

**Comment by Prajaktcs** [comment]
Changed and merged
