### ISSUE TITLE
1 or True

### ISSUE THREAD

**Issue by vforgione** [5thColumn/ansible-role-spark#5]
Why not use `yes` or `True`? `1` reads like an integer and not as a boolean bit.

https://github.com/Prajaktcs/ansible-role-spark/blob/master/defaults/main.yml#L15

**Comment by dm00000** [comment]
Please update the status of this issue. Is this still a problem or has it been addressed already in subsequent PR's?

**Comment by Prajaktcs** [comment]
Had removed property as a consequence of removing the handlers. Hence no longer an issue.
